# Generated by Django 2.0.2 on 2018-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='occur_date',
            field=models.DateTimeField(verbose_name='発生日時'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='report_date',
            field=models.DateTimeField(verbose_name='報告日時'),
        ),
    ]
