# Generated by Django 2.0.2 on 2018-03-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouble', '0002_auto_20180301_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleuser',
            name='stu_num',
            field=models.CharField(max_length=30, unique=True, verbose_name='学籍番号'),
        ),
    ]
