# Generated by Django 2.0.2 on 2018-03-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouble', '0003_auto_20180302_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleDateReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num', models.IntegerField()),
                ('troubles', models.ManyToManyField(to='trouble.Trouble')),
            ],
        ),
    ]
